-- Auto-generated by scripts/setup-users.mjs - DO NOT EDIT BY HAND
-- This file uses the real auth.users IDs created via the Admin API.

-- Organization
insert into organizations (id, name, slug, timezone)
values ('00000000-0000-0000-0000-000000000001', 'Acme Realty', 'acme-realty-demo', 'Asia/Kolkata')
on conflict (id) do nothing;

insert into integration_settings (organization_id, assignment_mode, service_mode)
values ('00000000-0000-0000-0000-000000000001', 'round_robin', 'dry-run')
on conflict (organization_id) do nothing;

-- Profiles (matched to real auth.users)
insert into profiles (id, organization_id, full_name, email, phone, role)
values ('305e5930-7271-4fa4-85ce-0459cbd89050', '00000000-0000-0000-0000-000000000001', 'Priya Admin', 'admin@acme.test', '+919900000001', 'admin')
on conflict (id) do update set full_name = excluded.full_name, role = excluded.role, organization_id = excluded.organization_id;
insert into profiles (id, organization_id, full_name, email, phone, role)
values ('ed981e85-87c2-4b21-903b-c47db343a23e', '00000000-0000-0000-0000-000000000001', 'Rohit Manager', 'manager@acme.test', '+919900000002', 'sales_manager')
on conflict (id) do update set full_name = excluded.full_name, role = excluded.role, organization_id = excluded.organization_id;
insert into profiles (id, organization_id, full_name, email, phone, role)
values ('c0d64f76-3629-4012-8364-bf51493460ef', '00000000-0000-0000-0000-000000000001', 'Anita Agent', 'anita@acme.test', '+919900000003', 'sales_agent')
on conflict (id) do update set full_name = excluded.full_name, role = excluded.role, organization_id = excluded.organization_id;
insert into profiles (id, organization_id, full_name, email, phone, role)
values ('8b0d3fea-ec2a-4424-be94-7bdc753caa02', '00000000-0000-0000-0000-000000000001', 'Vikram Agent', 'vikram@acme.test', '+919900000004', 'sales_agent')
on conflict (id) do update set full_name = excluded.full_name, role = excluded.role, organization_id = excluded.organization_id;
insert into profiles (id, organization_id, full_name, email, phone, role)
values ('da7cd2c9-69ce-47d9-8ce6-0bae9d2527ea', '00000000-0000-0000-0000-000000000001', 'Suresh Field', 'field@acme.test', '+919900000005', 'field_executive')
on conflict (id) do update set full_name = excluded.full_name, role = excluded.role, organization_id = excluded.organization_id;
insert into profiles (id, organization_id, full_name, email, phone, role)
values ('4177ecc6-5d16-47fc-884a-6e5a480286af', '00000000-0000-0000-0000-000000000001', 'Neha Social', 'social@acme.test', '+919900000006', 'social_media_manager')
on conflict (id) do update set full_name = excluded.full_name, role = excluded.role, organization_id = excluded.organization_id;

-- Convenient aliases for the rest of the seed
do $$
declare
  org_id uuid := '00000000-0000-0000-0000-000000000001';
  admin_id   uuid := '305e5930-7271-4fa4-85ce-0459cbd89050';
  mgr_id     uuid := 'ed981e85-87c2-4b21-903b-c47db343a23e';
  agent_a_id uuid := 'c0d64f76-3629-4012-8364-bf51493460ef';
  agent_v_id uuid := '8b0d3fea-ec2a-4424-be94-7bdc753caa02';
  field_id   uuid := 'da7cd2c9-69ce-47d9-8ce6-0bae9d2527ea';
  social_id  uuid := '4177ecc6-5d16-47fc-884a-6e5a480286af';
begin

-- ============================================================ Properties
insert into properties (id, organization_id, title, description, property_type, status, location, address, price, size_sqft, bedrooms, bathrooms, floor, furnishing, amenities, developer_name, created_by) values
('a0000001-0000-0000-0000-000000000001', org_id, '3BHK Luxury Apartment in Golf Course Road', 'Spacious 3BHK with modular kitchen, balcony, and city view.', 'apartment', 'available', 'Gurgaon, Sector 54', 'Golf Course Road, Sector 54, Gurgaon', 18500000, 1850, 3, 3, '12', 'semi', '{"Swimming Pool","Gym","Club House","24x7 Security","Power Backup"}', 'DLF', admin_id),
('a0000002-0000-0000-0000-000000000002', org_id, '2BHK Affordable Flat near Metro', 'Well-ventilated 2BHK close to Yellow Line metro.', 'apartment', 'available', 'Noida, Sector 76', 'Sector 76, Noida', 7200000, 1100, 2, 2, '5', 'unfurnished', '{"Lift","Park","CCTV"}', 'ATS', admin_id),
('a0000003-0000-0000-0000-000000000003', org_id, '4BHK Villa with Private Garden', 'Independent villa with garden, terrace, and 2 car parking.', 'villa', 'available', 'Gurgaon, Sushant Lok', 'Sushant Lok Phase 1, Gurgaon', 42000000, 3200, 4, 5, 'G+1', 'furnished', '{"Garden","Servant Room","Modular Kitchen","Private Pool"}', 'Independent', mgr_id),
('a0000004-0000-0000-0000-000000000004', org_id, 'Commercial Office Space', 'Plug-and-play office with 30 workstations.', 'commercial', 'available', 'Gurgaon, Cyber City', 'Cyber City Tower B, Gurgaon', 55000000, 2400, null, 2, '8', 'furnished', '{"Conference Room","Cafeteria","Reception"}', 'Embassy', mgr_id),
('a0000005-0000-0000-0000-000000000005', org_id, 'Plot in Upcoming Township', 'Residential plot in approved layout.', 'plot', 'available', 'Faridabad, Sector 88', 'Sector 88, Faridabad', 9500000, 1800, null, null, null, null, '{"Gated","Park","Wide Roads"}', 'BPTP', admin_id),
('a0000006-0000-0000-0000-000000000006', org_id, '3BHK Premium Apartment', 'Newly handed over project with all amenities.', 'apartment', 'available', 'Noida, Sector 150', 'Jaypee Greens, Noida', 13500000, 1650, 3, 2, '18', 'semi', '{"Pool","Gym","Spa","Sports Arena"}', 'Jaypee', admin_id),
('a0000007-0000-0000-0000-000000000007', org_id, '2BHK on Rent', 'Fully furnished 2BHK available for immediate move-in.', 'rental', 'available', 'Gurgaon, Sector 49', 'Uniworld Garden, Sector 49', 45000, 1200, 2, 2, '7', 'furnished', '{"AC","Wifi","Parking","Gym"}', 'Unitech', agent_a_id),
('a0000008-0000-0000-0000-000000000008', org_id, 'Studio Apartment Investor Special', 'Pre-leased studio with 6% yield.', 'apartment', 'hold', 'Gurgaon, Sector 65', 'M3M Heights, Sector 65', 6500000, 650, 1, 1, '10', 'furnished', '{"Lift","Pool","Gym"}', 'M3M', mgr_id),
('a0000009-0000-0000-0000-000000000009', org_id, 'Penthouse with Terrace', 'Top-floor 5BHK with private terrace and skyline view.', 'apartment', 'available', 'Gurgaon, MG Road', 'Ireo Grand Arch, Gurgaon', 82000000, 4100, 5, 5, '24', 'furnished', '{"Private Terrace","Pool","Concierge","Smart Home"}', 'Ireo', admin_id),
('a000000a-0000-0000-0000-00000000000a', org_id, 'Retail Shop Ground Floor', 'High-footfall retail unit in mixed-use complex.', 'commercial', 'available', 'Noida, Sector 18', 'DLF Mall of India Ext, Sector 18', 38000000, 1200, null, 1, 'G', 'unfurnished', '{"High Footfall","Glass Front","Power Backup"}', 'DLF', mgr_id)
on conflict (id) do nothing;

-- Property images (placeholder URLs)
insert into property_images (organization_id, property_id, storage_path, public_url, sort_order)
select org_id, p.id, 'demo/' || p.id || '/cover.jpg', 'https://picsum.photos/seed/' || replace(p.id::text,'-','') || '/800/600', 0
from properties p where p.organization_id = org_id;

-- ================================================================ Leads (20)
insert into leads (id, organization_id, full_name, phone, email, source, property_type, budget_min, budget_max, preferred_location, status, temperature, assigned_agent_id, notes, next_followup_at) values
('b0000001-0000-0000-0000-000000000001', org_id, 'Rahul Sharma',   '+919811100001', 'rahul1@example.com',  '36_acre',     'apartment',  7500000, 12000000, 'Gurgaon Golf Course Rd', 'new',                  'warm', agent_a_id, 'Looking for 3BHK near Golf Course Road',     now() + interval '1 day'),
('b0000002-0000-0000-0000-000000000002', org_id, 'Anjali Verma',   '+919811100002', 'anjali2@example.com', 'magicbricks', 'apartment',  5000000,  8000000, 'Noida Sector 76',        'contacted',            'warm', agent_v_id, 'Wants 2BHK ready-to-move',                   now() + interval '2 days'),
('b0000003-0000-0000-0000-000000000003', org_id, 'Karan Mehta',    '+919811100003', 'karan3@example.com',  'housing',     'villa',     35000000, 50000000, 'Gurgaon Sushant Lok',    'interested',           'hot',  agent_a_id, 'Has finance ready, wants villa',             now() + interval '6 hours'),
('b0000004-0000-0000-0000-000000000004', org_id, 'Pooja Iyer',     '+919811100004', 'pooja4@example.com',  'facebook',    'rental',       30000,    60000, 'Gurgaon Sector 49',      'site_visit_scheduled', 'hot',  agent_v_id, 'Needs furnished 2BHK rental',                now() + interval '1 day'),
('b0000005-0000-0000-0000-000000000005', org_id, 'Aman Gupta',     '+919811100005', 'aman5@example.com',   'instagram',   'plot',       7000000, 10000000, 'Faridabad Sector 88',    'new',                  'cold', agent_a_id, 'Investor for plot',                          now() + interval '3 days'),
('b0000006-0000-0000-0000-000000000006', org_id, 'Sneha Kapoor',   '+919811100006', 'sneha6@example.com',  'website',     'apartment', 12000000, 16000000, 'Noida Sector 150',       'negotiation',          'hot',  agent_v_id, 'Final negotiation on premium 3BHK',          now() + interval '12 hours'),
('b0000007-0000-0000-0000-000000000007', org_id, 'Vivek Rao',      '+919811100007', 'vivek7@example.com',  'whatsapp',    'commercial',40000000, 60000000, 'Gurgaon Cyber City',     'interested',           'warm', agent_a_id, 'Office space for IT firm',                   now() + interval '2 days'),
('b0000008-0000-0000-0000-000000000008', org_id, 'Neeraj Sethi',   '+919811100008', 'neeraj8@example.com', 'referral',    'apartment',  5000000,  7000000, 'Gurgaon Sector 65',      'contacted',            'warm', agent_v_id, 'Studio investment property',                 now() + interval '1 day'),
('b0000009-0000-0000-0000-000000000009', org_id, 'Ritika Bhatt',   '+919811100009', 'ritika9@example.com', 'manual',      'apartment',  8000000, 11000000, 'Noida',                  'new',                  'warm', agent_a_id, 'Walked in to office',                        now() + interval '3 days'),
('b000000a-0000-0000-0000-00000000000a', org_id, 'Manoj Tiwari',   '+919811100010', 'manoj10@example.com', '36_acre',     'villa',     30000000, 45000000, 'Gurgaon',                'interested',           'hot',  agent_v_id, 'Looking at villas this weekend',             now() + interval '8 hours'),
('b000000b-0000-0000-0000-00000000000b', org_id, 'Deepak Khanna',  '+919811100011', 'deepak11@example.com','magicbricks', 'plot',       6000000, 10000000, 'Faridabad',              'not_responding',       'cold', agent_a_id, 'Tried 3 calls, no answer',                   now() + interval '5 days'),
('b000000c-0000-0000-0000-00000000000c', org_id, 'Shweta Joshi',   '+919811100012', 'shweta12@example.com','facebook',    'apartment',  4500000,  6500000, 'Noida Sector 76',        'contacted',            'warm', agent_v_id, 'Interested in 2BHK',                         now() + interval '2 days'),
('b000000d-0000-0000-0000-00000000000d', org_id, 'Arjun Nair',     '+919811100013', 'arjun13@example.com', 'housing',     'apartment', 15000000, 20000000, 'Gurgaon MG Road',        'interested',           'hot',  agent_a_id, 'High-budget penthouse seeker',               now() + interval '1 day'),
('b000000e-0000-0000-0000-00000000000e', org_id, 'Riya Saxena',    '+919811100014', 'riya14@example.com',  'instagram',   'rental',       25000,    45000, 'Gurgaon',                'new',                  'warm', agent_v_id, 'Newly relocated, urgent rental',             now() + interval '6 hours'),
('b000000f-0000-0000-0000-00000000000f', org_id, 'Sumit Yadav',    '+919811100015', 'sumit15@example.com', 'website',     'apartment',  9000000, 13000000, 'Noida Sector 150',       'site_visit_scheduled', 'hot',  agent_a_id, 'Site visit Saturday',                        now() + interval '2 days'),
('b0000010-0000-0000-0000-000000000010', org_id, 'Tanya Roy',      '+919811100016', 'tanya16@example.com', 'referral',    'villa',     20000000, 30000000, 'Gurgaon',                'won',                  'hot',  agent_v_id, 'Closed villa deal',                          null),
('b0000011-0000-0000-0000-000000000011', org_id, 'Mohit Bansal',   '+919811100017', 'mohit17@example.com', '36_acre',     'commercial',30000000, 45000000, 'Noida',                  'lost',                 'cold', agent_a_id, 'Went with competitor',                       null),
('b0000012-0000-0000-0000-000000000012', org_id, 'Nidhi Pillai',   '+919811100018', 'nidhi18@example.com', 'magicbricks', 'apartment', 10000000, 14000000, 'Gurgaon Sector 54',      'interested',           'warm', agent_v_id, 'Compares 2-3 options weekly',                now() + interval '4 days'),
('b0000013-0000-0000-0000-000000000013', org_id, 'Hemant Singh',   '+919811100019', 'hemant19@example.com','manual',      'apartment',  6500000,  9000000, 'Faridabad',              'new',                  'warm', agent_a_id, 'Came via walk-in',                           now() + interval '3 days'),
('b0000014-0000-0000-0000-000000000014', org_id, 'Ankit Malhotra', '+919811100020', 'ankit20@example.com', 'facebook',    'apartment', 11000000, 15000000, 'Gurgaon',                'contacted',            'hot',  agent_v_id, 'Very engaged, wants demo today',             now() + interval '4 hours')
on conflict (id) do nothing;

-- Sample calls
insert into calls (organization_id, lead_id, agent_id, status, outcome, duration_seconds, started_at, ended_at, notes, is_dry_run) values
(org_id, 'b0000001-0000-0000-0000-000000000001', agent_a_id, 'completed', 'connected',  184, now() - interval '2 hours', now() - interval '2 hours' + interval '184 seconds', 'First contact, interested', true),
(org_id, 'b0000003-0000-0000-0000-000000000003', agent_a_id, 'completed', 'interested', 420, now() - interval '5 hours', now() - interval '5 hours' + interval '7 minutes',   'Will visit on Sat',         true),
(org_id, 'b000000b-0000-0000-0000-00000000000b', agent_a_id, 'completed', 'no_answer',    0, now() - interval '1 day',   now() - interval '1 day',                            'Did not pick up',           true),
(org_id, 'b0000004-0000-0000-0000-000000000004', agent_v_id, 'completed', 'connected',  310, now() - interval '6 hours', now() - interval '6 hours' + interval '310 seconds', 'Fixed site visit',          true);

-- Sample follow-ups
insert into followups (organization_id, lead_id, assigned_to, type, status, due_at, template_name, notes, created_by) values
(org_id, 'b0000001-0000-0000-0000-000000000001', agent_a_id, 'whatsapp', 'pending',   now() + interval '1 day',     'check_in',    'Send 3BHK photo set',                admin_id),
(org_id, 'b0000003-0000-0000-0000-000000000003', agent_a_id, 'call',     'pending',   now() + interval '6 hours',   'callback',    'Confirm Saturday visit',             mgr_id),
(org_id, 'b0000006-0000-0000-0000-000000000006', agent_v_id, 'email',    'pending',   now() + interval '12 hours',  'negotiation', 'Send revised offer letter',          mgr_id),
(org_id, 'b0000008-0000-0000-0000-000000000008', agent_v_id, 'whatsapp', 'completed', now() - interval '1 day',     'check_in',    'Customer asked for more options',    mgr_id);

-- Sample attendance
insert into attendance (organization_id, user_id, check_in_time, check_out_time, check_in_latitude, check_in_longitude, check_out_latitude, check_out_longitude, status) values
(org_id, agent_a_id, now() - interval '8 hours',           now() - interval '15 minutes', 28.4595, 77.0266, 28.4595, 77.0266, 'present'),
(org_id, agent_v_id, now() - interval '7 hours 30 minutes', null,                          28.4744, 77.0497, null,    null,    'present'),
(org_id, field_id,   now() - interval '6 hours 45 minutes', null,                          28.4089, 77.3178, null,    null,    'late');

-- Sample social posts
insert into social_posts (organization_id, title, caption, platform, status, scheduled_at, assigned_to, created_by) values
(org_id, 'Weekend Property Walkthrough', 'Tour this stunning 3BHK in Gurgaon Golf Course Rd this weekend. DM for details.', 'instagram_reel', 'scheduled', now() + interval '2 days', social_id, admin_id),
(org_id, 'New Project Launch',           'Pre-launch offer on Sector 150 premium project. Limited units.',                  'facebook_post',  'draft',     null,                       social_id, admin_id),
(org_id, 'Customer Testimonial',         'Hear from Tanya about her dream villa journey.',                                  'instagram_post', 'idea',      null,                       social_id, admin_id);

-- Activities (timeline entries)
insert into activities (organization_id, actor_id, type, lead_id, payload)
select org_id, l.assigned_agent_id, 'lead_created', l.id, jsonb_build_object('source', l.source)
from leads l where l.organization_id = org_id;

-- Notifications
insert into notifications (organization_id, user_id, title, body, type, link) values
(org_id, agent_a_id, 'New lead assigned', 'Rahul Sharma from 36 Acre. Tap to call.',  'lead_assigned',        '/leads/b0000001-0000-0000-0000-000000000001'),
(org_id, agent_v_id, 'Follow-up due',     'Anjali Verma is due for follow-up',         'followup_due',         '/leads/b0000002-0000-0000-0000-000000000002'),
(org_id, mgr_id,     'Site visit',        'Pooja Iyer - site visit scheduled tomorrow','site_visit_scheduled', '/leads/b0000004-0000-0000-0000-000000000004');

end$$;
